[package]
name = "nginee_event_loop"
version = "0.1.0"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
futures = { version =  "0.3.5", default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
governor = { version = "0.2.0", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
async-std = { version = "1.6.0-beta.1", optional = true }
futures-test = { version = "0.3.5", optional = true }

[features]
default = []
rate_limit = ["async-std/unstable", "governor"]
