[package]
name = "nginee_event_loop"
version = "0.1.0"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
futures = { version =  "0.3.5", default-features = false }
governor = { version = "0.2.0", default-features = false, optional = true, features = ["std"] }

# Requires `cargo build -Z features=itarget`
#
# See <https://github.com/rust-lang/cargo/issues/7914>
# [target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# dashmap and quanta both rely on `libc`, which is not available in WASM
# governor = { version = "0.2.0", default-features = false, optional = true, features = ["dashmap", "quanta"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
governor = { version = "0.2.0", default-features = false, optional = true }

[features]
default = []
rate_limit = ["governor"]

# Native builds
dashmap = ["governor/dashmap"]
quanta = ["governor/quanta"]

# WASM
wasm-bindgen = ["governor/wasm-bindgen"]
