[package]
name = "nginee_event_loop"
version = "0.1.0"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
async-std = { version = "1.6.0-beta.1", optional = true }
futures = { version =  "0.3.5", default-features = false }
futures-test = { version = "0.3.5", optional = true }

[features]
default = []
rate_limit = [
    "async-std",
    "async-std/unstable",
    "futures-test",
]
