[package]
name = "workspace_tests"
version = "0.1.0"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2018"

[dev-dependencies]
nginee = { path = "../..", features = ["event_loop"] }
smol = "0.1.4"
