on:
  push:
    branches:
      - master

name: Publish Book

jobs:
  publish_examples_wasm:
    name: Build examples (WASM)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: 'Install `wasm-pack`'
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'

      - name: 'Build examples'
        run: |
          for example in $(ls examples)
          do wasm-pack build --target web --out-dir "../../doc/src/pkg examples/${example}"
          done

      # Build and publish book
      - name: Install `mdbook`
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: latest

      - run: mdbook build
      - run: mdbook test

      - name: Publish to `gh-pages`
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/book
