on:
  push:
    branches:
      - master

name: User Guide

jobs:
  publish_examples_wasm:
    name: Build examples (WASM)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - # FIXME: Switch back when actions-rs/toolchain#{209,220,222} is merged
        uses: r3-os/actions-rust-toolchain@a862b6623c178b43a3135516442a5f72fb5c1877
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: 'Install `wasm-pack`'
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'

      - name: 'Build examples'
        run: |
          for example in $(ls examples)
          do wasm-pack build --target web --out-dir "../../doc/src/pkg" "examples/${example}" --release
          done

      # Build and publish book
      - name: Install `mdbook`
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: latest

      - run: mdbook build doc
      - run: mdbook test doc
      # We *do* want to include the built wasm files.
      - run: rm -f ./doc/book/pkg/.gitignore

      - name: Publish to `gh-pages`
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/book
          force_orphan: true
